// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoB8sYoVoFVvFf_zqmcUf_-IUoLHO50kQ',
    appId: '1:951033930421:web:539d69ae78f0047d6514fc',
    messagingSenderId: '951033930421',
    projectId: 'chat-app-760c0',
    authDomain: 'chat-app-760c0.firebaseapp.com',
    storageBucket: 'chat-app-760c0.appspot.com',
    measurementId: 'G-0NN9TSNNV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbwN9bnCYsCXJYHRpQA8zzwdKektuRH18',
    appId: '1:951033930421:android:d30b44316ff666106514fc',
    messagingSenderId: '951033930421',
    projectId: 'chat-app-760c0',
    storageBucket: 'chat-app-760c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgwqKGqMFXnnnYL_IzUy2fyK9YO9sjP58',
    appId: '1:951033930421:ios:3de449d7f3172e016514fc',
    messagingSenderId: '951033930421',
    projectId: 'chat-app-760c0',
    storageBucket: 'chat-app-760c0.appspot.com',
    iosClientId: '951033930421-267nsv5j78qreort5pad5n8n777ic33f.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgwqKGqMFXnnnYL_IzUy2fyK9YO9sjP58',
    appId: '1:951033930421:ios:3de449d7f3172e016514fc',
    messagingSenderId: '951033930421',
    projectId: 'chat-app-760c0',
    storageBucket: 'chat-app-760c0.appspot.com',
    iosClientId: '951033930421-267nsv5j78qreort5pad5n8n777ic33f.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineApp',
  );
}
